DATABASE_HOST = "localhost"
DATABASE_PORT = 13306
DATABASE_USER = "root"
DATABASE_PASSWORD = "root"
DATABASE_NAME = "cybereye"
DATABASE_URL = f"mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}?charset=utf8mb4"

GEOIP_DATABASES_AUTO_UPDATE = False
