services:
  app:
    build: .
    restart: always
    ports:
      - "23333:8000"
    volumes:
      - .:/app
      - /dev/null:/app/.env
    environment:
      - DATABASE_HOST=db
      - ROLE=server
      - TZ=Asia/Shanghai
  scheduler:
    build: .
    restart: always
    volumes:
      - .:/app
      - /dev/null:/app/.env
    environment:
      - DATABASE_HOST=db
      - ROLE=scheduler
      - TZ=Asia/Shanghai
  worker:
    build: .
    restart: always
    volumes:
      - .:/app
      - /dev/null:/app/.env
    environment:
      - DATABASE_HOST=db
      - ROLE=worker
      - TZ=Asia/Shanghai
    deploy:
      replicas: 8
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cybereye
      - TZ=Asia/Shanghai
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
    driver: local
